# Generated by Django 5.1.7 on 2025-06-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('sold', 'Sold'), ('pending', 'Pending')], default='sale', max_length=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('inspection_requested', models.BooleanField(default=False)),
            ],
        ),
    ]
