# Generated by Django 5.1.7 on 2025-06-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='inspection_requested',
        ),
    ]
