# Generated by Django 5.1.7 on 2025-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_property_inspection_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Bank Payment Info',
                'verbose_name_plural': 'Bank Payment Info',
            },
        ),
        migrations.CreateModel(
            name='CryptoPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Optional payment instructions', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='tour_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
