# Generated by Django 5.1.7 on 2025-06-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_bankpaymentinfo_cryptopaymentinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpaymentinfo',
            name='expiration_minutes',
        ),
        migrations.RemoveField(
            model_name='bankpaymentinfo',
            name='transfer_amount',
        ),
    ]
